const data = {
  products: [
    {
      name: 'Red Hoodie',
      slug: 'Red-Hoodie',
      category: 'Men',
      image: '/images/red hoodie.jpg',
      price: 3990,
      sizeS: 5,
      sizeM: 5,
      sizeL: 5,
      sizeXl: 5,
      rating: 4.5,
      numReviews: 5,
      description: 'High quality product',
    },
    {
      name: 'Long Sleeve Denim Shirt',
      slug: 'Long-Sleeve-Denim-Shirt',
      category: 'Men',
      image: '/images/long sleeve denim shirt (1).jpg',
      price: 3990,
      sizeS: 5,
      sizeM: 5,
      sizeL: 5,
      sizeXl: 5,
      rating: 4.5,
      numReviews: 5,
      description: 'High quality product',
    },
    {
      name: 'Grey Tshirt',
      slug: 'Grey-Tshirt',
      category: 'Men',
      image: '/images/grey tshirt.jpg',
      price: 3990,
      sizeS: 5,
      sizeM: 5,
      sizeL: 5,
      sizeXl: 5,
      rating: 4.5,
      numReviews: 5,
      description: 'High quality product',
    },
  ],
};
export default data;
